---
title: A Blog 4u
email: 4u@4dandies.com
description: 'Write an awesome description for your new site here. You can edit this
  line in jekyll.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.'
baseurl: ""
url: http://www.4dandies.com
destination: "../public/static"
twitter_username: real4dandies
github_username: 4dandies
markdown: kramdown
permalink: pretty
gems:
- octopress-paginate

collections:
 brands:
  output: true
 posts:
  output: true
  permalink: blog/:year/:month/:day/:title/

facebook: 'https://www.facebook.com/4dandies/'
instagram: 'https://www.instagram.com/4dandies/'
google_plus: 'https://plus.google.com/u/0/b/100144721967412221214/100144721967412221214'
youtube: 'https://www.youtube.com/channel/UCdoe0MItp8CJd3x1axvo0XA'
twitter: 'https://twitter.com/real4dandies'
pinterest: 'https://pt.pinterest.com/4dandies/'